### ISSUE TITLE
How to use anti-interference algorithm ?

### ISSUE THREAD

**Issue by nyxrobotics** [hypersen/HPS3D_SDK#1]
I bought two HPS-3D160U.
When I use two sensors at the same time, they interference each other.
How can I setup anti-interference algorithm written in seeedstudio's website?
(https://www.seeedstudio.com/HPS-3D160-Solid-State-LiDAR.html)

**Comment by nyxrobotics** [comment]
I am running your latest ROS example.

**Comment by nyxrobotics** [comment]
![Peek 2019-10-24 12-54](https://user-images.githubusercontent.com/19720932/67452213-7b262680-f65d-11e9-8a78-d1931a0300dc.gif)

**Comment by hypersen** [comment]
Please read HPS3D_RM001_LiDAR software manual_EN.pdf 5.7 Mutual interference for multi device. Use HPS3D160-Client.exe to get Version and SerialNo. Send it to me to confirm whether the hardware version supports multi-machine work;

**Comment by nyxrobotics** [comment]
<img width="540" alt="hps" src="https://user-images.githubusercontent.com/19720932/67538841-42e51d80-f71b-11e9-8b38-3adc2f8e7737.png">
Here.

**Comment by nyxrobotics** [comment]
<img width="396" alt="hps2" src="https://user-images.githubusercontent.com/19720932/67540193-7a55c900-f71f-11e9-9b9e-c7466adc4dc5.png">
I changed "Multi Camera ID", and it woks perfectly. Thank you!
