### ISSUE TITLE
Add aarch64/arm64 shared libs

### ISSUE THREAD

**Issue by FelipMarti** [hypersen/HPS3D_SDK#2]
Hello,

The ARM shared library is for 32-bit processors:
libhps3d_arm.so: ELF 32-bit LSB shared object, ARM

We are using the Nvidia [Jetson Nano Developer Kit](https://developer.nvidia.com/embedded/jetson-nano-developer-kit) to connect an array of HPS3D-160 cameras. This kit uses ARM aarch64 architecture.

Could you please build and provide the shared libraries for ARM aarch64?

Thank you

**Comment by hypersen** [comment]
Ok, I have updated hps3d_aarch64.so, please download again！

**Comment by FelipMarti** [comment]
Great! thank you so much!
