### ISSUE TITLE
Using Obstacle Detection and ROIs

### ISSUE THREAD

**Issue by Superheitmann** [hypersen/HPS3D_SDK#3]
Dear Hypersen Team,

the SDK provided for the HPS3D_160 has just the functionality needed for my project. However, I'm having trouble using it correctly. 

I'm trying to either setup obstacle detection or split the view of the HPS3D_160 into multiple segments to get the corresponding average distance. Either way I'm doing something wrong.

My current steps are the following:

```
HPS3D_Connect(&handle);
HPS3D_ConfigInit(&handle);

ROIConfTypeDef roiConf; //Define an arbitrary Pixel area for a test
roiConf.roi_id = 0;
roiConf.left_top_x = 0;
roiConf.left_top_y = 0;
roiConf.right_bottom_x = 10;
roiConf.right_bottom_y = 20;

HPS3D_SetROIRegion(&handle, roiConf);
HPS3D_SetROIEnable(&handle, roiConf.roi_id, true);
HPS3D_SetMeasurePacketType(ROI_DATA_PACKET);
HPS3D_SingleMeasurement(&handle);
```

The moment I try to start measurements, be it synchronous or asynchronous, the SDK throws a `SIGSEGV` exception. This does not happen if I disable the ROI via 
`HPS3D_SetROIEnable(&handle, roiConf.roi_id, false);`

A similar problem occurs with the obstacle detection. I used `HPS3D_SetPointCloudEn (true);` and `HPS3D_ObstacleConfigInit (...);` where I inserted my ObstacleConfig. However the error could very well be that I don't know what the frame_head and frame_size within the `ObstacleConfigTypedef` mean. Therefore. I basically tried arbitrary values, which were quite possibly invalid.

If you could help me find the correct implementation I'd be very thankful.

Yours sincerely
Superheitmann

**Comment by hypersen** [comment]
Hi：
    It is recommended to use HPS3D-Client.exe to configure ROI and other related functions. After configuration is complete, click Advance-> save to user profile, https://github.com/hypersen/HPS3D160-Client;
When using the ROI function, the SDK needs to call HPS3D_SetMeasurePacketType (ROI_DATA_PACKET) before HPS3D_ConfigInit; and call the ROI related setting interface before HPS3D_SetRunMode;
